
package it.water.service.discovery.service.rest;

import it.water.service.discovery.api.*;
import it.water.service.discovery.api.rest.*;
import it.water.service.discovery.model.*;

import it.water.core.api.service.BaseEntityApi;
import it.water.service.rest.persistence.BaseEntityRestApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.*;


import lombok.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for ServiceRegistration entity.
 *
 */
@FrameworkRestController(referredRestApi = ServiceRegistrationRestApi.class)
public class ServiceRegistrationRestControllerImpl extends BaseEntityRestApi<ServiceRegistration> implements ServiceRegistrationRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(ServiceRegistrationRestControllerImpl.class.getName());
    
    @Inject
    @Setter
    private ServiceRegistrationApi serviceRegistrationApi;
    @Override
    protected BaseEntityApi<ServiceRegistration> getEntityService() {
        return serviceRegistrationApi;
    }
    //All CRUD methods are already exposed by ServiceRegistrationRestApi interface with JAXRS Annotatiosn
    //if you need to check which methods are exposed please go to it.water.service.discovery.api.rest.ServiceRegistration

    //todo add custom exposed methods or override CRUD operations
    //ATTENTION: use always ServiceRegistrationApi in order to ensure the user is requesting operations has the right privileges to do it

}
