
package it.water.service.discovery.service.rest.spring;

import it.water.service.discovery.service.rest.ServiceRegistrationRestControllerImpl;
import it.water.core.api.model.*;
import it.water.core.api.repository.*;
import it.water.core.api.repository.query.*;
import it.water.service.discovery.api.*;
import it.water.service.discovery.model.*;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for ServiceRegistration entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class ServiceRegistrationSpringRestControllerImpl extends ServiceRegistrationRestControllerImpl implements ServiceRegistrationSpringRestApi {
        @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ServiceRegistration save(ServiceRegistration entity) {
        return super.save(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ServiceRegistration update(ServiceRegistration entity) {
        return super.update(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public ServiceRegistration find(long id) {
        return super.find(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<ServiceRegistration> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<ServiceRegistration> findAll() {
        return super.findAll();
    }
    }
