package it.water.service.discovery.service;

import it.water.service.discovery.api.*;
import it.water.service.discovery.model.*;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.api.repository.query.Query;
import it.water.core.interceptors.annotations.*;

import it.water.repository.service.BaseEntitySystemServiceImpl;

import lombok.*;

import java.util.*;
import java.util.Date;
import java.util.UUID;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Supplier;


/**
 * @Generated by Water Generator
 * System Service Api Class for ServiceRegistration entity.
 *
 * <p>All public operations are serialized through {@link #repositoryLock} (coarse-grained locking).
 * This is intentional and acceptable for the expected traffic profile of a service-discovery registry
 * (register / deregister / heartbeat / cleanup — typically well below 100 operations/sec).
 * The lock eliminates TOCTOU races between the heartbeat update and the cleanup sweep without
 * introducing per-entity or optimistic-locking complexity.
 * Revisit with per-{@code serviceName} lock-striping only if sustained throughput exceeds
 * ~100 registrations/sec under profiling.
 */
@FrameworkComponent
public class ServiceRegistrationSystemServiceImpl extends BaseEntitySystemServiceImpl<ServiceRegistration> implements ServiceRegistrationSystemApi {
    private final ReentrantLock repositoryLock = new ReentrantLock();

    @Inject
    @Getter
    @Setter
    private ServiceRegistrationRepository repository;

    @Inject
    @Setter
    /*
     * Reserved generated dependency. The current internal registration,
     * heartbeat and cleanup flow does not need component filtering, but we keep
     * the injection point explicit so future ServiceDiscovery custom queries can
     * reuse the generator-compatible SystemService shape without another API
     * break.
     */
    private ComponentFilterBuilder componentFilterBuilder;

    public ServiceRegistrationSystemServiceImpl() {
        super(ServiceRegistration.class);
    }

    @Override
    public ServiceRegistration registerInternal(ServiceRegistration service) {
        return withRepositoryLock(() -> {
            getLog().debug("Registering service internally: {}", service.getServiceName());
            service.setLastHeartbeat(new Date());
            service.setStatus(ServiceStatus.UP);
            if (service.getInstanceId() == null || service.getInstanceId().isBlank()) {
                service.setInstanceId(UUID.randomUUID().toString());
            }
            return repository.persist(service);
        });
    }

    @Override
    public void deregisterByKey(String serviceName, String instanceId) {
        withRepositoryLock(() -> {
            getLog().debug("Deregistering service internally by key: {} / {}", serviceName, instanceId);
            repository.removeByServiceNameAndInstanceId(serviceName, instanceId);
        });
    }

    @Override
    public boolean updateHeartbeatInternal(String serviceName, String instanceId) {
        return withRepositoryLock(() -> {
            getLog().debug("Updating heartbeat internally for service: {} instance: {}", serviceName, instanceId);
            return repository.updateHeartbeatAndStatus(serviceName, instanceId, new Date(), ServiceStatus.UP);
        });
    }

    @Override
    public Map<String, ServiceStatus> performBatchHealthCheck() {
        return withRepositoryLock(() -> {
            getLog().debug("Performing batch health check on all services");
            Map<String, ServiceStatus> results = new HashMap<>();
            List<ServiceRegistration> allServices = repository.findByStatus(ServiceStatus.UP);
            for (ServiceRegistration service : allServices) {
                results.put(service.getInstanceId(), service.getStatus());
            }
            return results;
        });
    }

    @Override
    public void cleanupInactiveServices(int inactiveThresholdSeconds) {
        withRepositoryLock(() -> {
            getLog().debug("Cleaning up inactive services with threshold: {} seconds", inactiveThresholdSeconds);
            Date thresholdDate = new Date(System.currentTimeMillis() - (inactiveThresholdSeconds * 1000L));
            List<ServiceRegistration> inactiveServices = repository.findByLastHeartbeatBeforeAndStatusNot(thresholdDate, ServiceStatus.OUT_OF_SERVICE);
            for (ServiceRegistration service : inactiveServices) {
                repository.updateStatus(service.getServiceName(), service.getInstanceId(), ServiceStatus.OUT_OF_SERVICE);
            }
        });
    }

    @Override
    public List<ServiceRegistration> findByStatus(ServiceStatus status) {
        return withRepositoryLock(() -> {
            getLog().debug("Finding services by status: {}", status);
            return new ArrayList<>(repository.findByStatus(status));
        });
    }

    @Override
    public List<ServiceRegistration> findByCustomQuery(Query query) {
        return withRepositoryLock(() -> {
            getLog().debug("Finding services by custom query");
            return new ArrayList<>(repository.findAll(-1, 1, query, null).getResults());
        });
    }

    @Override
    public void updateStatus(String serviceName, String instanceId, ServiceStatus status) {
        withRepositoryLock(() -> {
            getLog().debug("Updating status for service: {} instance: {} to: {}", serviceName, instanceId, status);
            repository.updateStatus(serviceName, instanceId, status);
        });
    }

    private void withRepositoryLock(Runnable action) {
        repositoryLock.lock();
        try {
            action.run();
        } finally {
            repositoryLock.unlock();
        }
    }

    private <T> T withRepositoryLock(Supplier<T> action) {
        repositoryLock.lock();
        try {
            return action.get();
        } finally {
            repositoryLock.unlock();
        }
    }

}
