package it.water.service.discovery.service;

import it.water.service.discovery.api.*;
import it.water.service.discovery.model.*;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.api.repository.query.Query;
import it.water.core.interceptors.annotations.*;

import it.water.repository.service.BaseEntitySystemServiceImpl;

import lombok.*;

import java.util.*;
import java.util.Date;


/**
 * @Generated by Water Generator
 * System Service Api Class for ServiceRegistration entity.
 *
 */
@FrameworkComponent
public class ServiceRegistrationSystemServiceImpl extends BaseEntitySystemServiceImpl<ServiceRegistration> implements ServiceRegistrationSystemApi {
    @Inject
    @Getter
    @Setter
    private ServiceRegistrationRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public ServiceRegistrationSystemServiceImpl() {
        super(ServiceRegistration.class);
    }

    @Override
    public ServiceRegistration registerInternal(ServiceRegistration service) {
        getLog().debug("Registering service internally: {}", service.getServiceName());
        return repository.persist(service);
    }

    @Override
    public Map<String, ServiceStatus> performBatchHealthCheck() {
        getLog().debug("Performing batch health check on all services");
        Map<String, ServiceStatus> results = new HashMap<>();
        List<ServiceRegistration> allServices = repository.findByStatus(ServiceStatus.UP);
        for (ServiceRegistration service : allServices) {
            // Simplified health check - in a real implementation, you would make HTTP calls
            results.put(service.getInstanceId(), service.getStatus());
        }
        return results;
    }

    @Override
    public void cleanupInactiveServices(int inactiveThresholdSeconds) {
        getLog().debug("Cleaning up inactive services with threshold: {} seconds", inactiveThresholdSeconds);
        Date thresholdDate = new Date(System.currentTimeMillis() - (inactiveThresholdSeconds * 1000L));
        List<ServiceRegistration> inactiveServices = repository.findByLastHeartbeatBefore(thresholdDate);
        for (ServiceRegistration service : inactiveServices) {
            repository.updateStatus(service.getServiceName(), service.getInstanceId(), ServiceStatus.OUT_OF_SERVICE);
        }
    }

    @Override
    public List<ServiceRegistration> findByCustomQuery(Query query) {
        getLog().debug("Finding services by custom query");
        return new ArrayList<>(repository.findAll(-1, 1, query, null).getResults());
    }

    @Override
    public void updateStatus(String serviceName, String instanceId, ServiceStatus status) {
        getLog().debug("Updating status for service: {} instance: {} to: {}", serviceName, instanceId, status);
        repository.updateStatus(serviceName, instanceId, status);
    }

}