package it.water.service.discovery.service;

import it.water.service.discovery.api.*;
import it.water.service.discovery.model.*;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.*;

import java.util.*;
import java.util.stream.Collectors;


/**
 * @Generated by Water Generator
 * Service Api Class for ServiceRegistration entity.
 *
 */
@FrameworkComponent
public class ServiceRegistrationServiceImpl extends BaseEntityServiceImpl<ServiceRegistration> implements ServiceRegistrationApi {

    @Inject
    @Getter
    @Setter
    private ServiceRegistrationSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ServiceRegistrationRepository repository;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public ServiceRegistrationServiceImpl() {
        super(ServiceRegistration.class);
    }

    @Override
    public ServiceRegistration register(ServiceRegistration service) {
        getLog().debug("Registering service: {}", service.getServiceName());
        // Set initial values - registrationTime is handled by @PrePersist in the entity
        service.setLastHeartbeat(new Date());
        service.setStatus(ServiceStatus.UP);
        if (service.getInstanceId() == null) {
            service.setInstanceId(UUID.randomUUID().toString());
        }
        return systemService.save(service);
    }

    @Override
    public void deregister(String serviceName, String instanceId) {
        getLog().debug("Deregistering service: {} instance: {}", serviceName, instanceId);
        ServiceRegistration service = repository.findByServiceNameAndInstanceId(serviceName, instanceId);
        if (service != null) {
            systemService.remove(service.getId());
        }
    }

    @Override
    public List<ServiceRegistration> findByServiceName(String serviceName) {
        getLog().debug("Finding services by name: {}", serviceName);
        return repository.findByServiceName(serviceName);
    }

    @Override
    public List<ServiceRegistration> findByTags(Set<String> tags) {
        getLog().debug("Finding services by tags: {}", tags);
        if (tags == null || tags.isEmpty()) {
            return Collections.emptyList();
        }
        // Find services that contain any of the specified tags
        Set<ServiceRegistration> results = new HashSet<>();
        for (String tag : tags) {
            results.addAll(repository.findByTagsContaining(tag));
        }
        return new ArrayList<>(results);
    }

    @Override
    public List<ServiceRegistration> findByStatus(ServiceStatus status) {
        getLog().debug("Finding services by status: {}", status);
        return repository.findByStatus(status);
    }

    @Override
    public List<ServiceRegistration> getAvailableServices() {
        getLog().debug("Getting all available services");
        return findByStatus(ServiceStatus.UP);
    }

    @Override
    public void updateHeartbeat(String serviceName, String instanceId) {
        getLog().debug("Updating heartbeat for service: {} instance: {}", serviceName, instanceId);
        repository.updateHeartbeat(serviceName, instanceId, new Date());
        // Also update status to UP if it was different
        repository.updateStatus(serviceName, instanceId, ServiceStatus.UP);
    }

    @Override
    public ServiceStatus performHealthCheck(String serviceName, String instanceId) {
        getLog().debug("Performing health check for service: {} instance: {}", serviceName, instanceId);
        ServiceRegistration service = repository.findByServiceNameAndInstanceId(serviceName, instanceId);
        if (service == null) {
            return ServiceStatus.OUT_OF_SERVICE;
        }
        // Simplified health check - in a real implementation, you would make HTTP calls to the health endpoint
        // For now, just return the current status
        return service.getStatus();
    }
}
