package it.water.service.discovery.api;

import it.water.core.api.service.BaseEntityApi;
import it.water.service.discovery.model.ServiceRegistration;
import it.water.service.discovery.model.ServiceStatus;

import java.util.List;
import java.util.Set;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for service registration
 * and allows interaction with it through a permission system.
 *
 * API with permission checks - requires authenticated user with appropriate permissions.
 */
public interface ServiceRegistrationApi extends BaseEntityApi<ServiceRegistration> {

    /**
     * Registers a new service instance in the Service Discovery system.
     *
     * @param service the service registration to create
     * @return the registered service with generated ID and instanceId
     */
    ServiceRegistration register(ServiceRegistration service);

    /**
     * Deregisters a service instance from the Service Discovery system.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     */
    void deregister(String serviceName, String instanceId);

    /**
     * Finds all instances of a service by its name.
     *
     * @param serviceName the name of the service
     * @return list of service instances
     */
    List<ServiceRegistration> findByServiceName(String serviceName);

    /**
     * Finds services that contain specific tags.
     *
     * @param tags the tags to search for
     * @return list of services matching the tags
     */
    List<ServiceRegistration> findByTags(Set<String> tags);

    /**
     * Finds services with a specific status.
     *
     * @param status the service status
     * @return list of services with the given status
     */
    List<ServiceRegistration> findByStatus(ServiceStatus status);

    /**
     * Retrieves all services that are currently available (status = UP).
     *
     * @return list of available services
     */
    List<ServiceRegistration> getAvailableServices();

    /**
     * Updates the heartbeat timestamp for a service instance.
     * Also updates the status to UP if it was in a different state.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     */
    void updateHeartbeat(String serviceName, String instanceId);

    /**
     * Performs a health check on a service instance by calling its health endpoint.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     * @return the service status after the health check
     */
    ServiceStatus performHealthCheck(String serviceName, String instanceId);
}