package it.water.service.discovery.api;

import it.water.core.api.repository.BaseRepository;
import it.water.service.discovery.model.ServiceRegistration;
import it.water.service.discovery.model.ServiceStatus;

import java.util.Date;
import java.util.List;

/**
 * @Generated by Water Generator
 * Interface component for ServiceRegistration Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 * Provides custom query methods for service discovery operations.
 */
public interface ServiceRegistrationRepository extends BaseRepository<ServiceRegistration> {

    /**
     * Finds a service registration by service name and instance ID.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     * @return the service registration, or null if not found
     */
    ServiceRegistration findByServiceNameAndInstanceId(String serviceName, String instanceId);

    /**
     * Removes a service registration by logical key using a single repository operation.
     *
     * @param serviceName the logical service name
     * @param instanceId the runtime instance id
     * @return true if a row was removed, false otherwise
     */
    boolean removeByServiceNameAndInstanceId(String serviceName, String instanceId);

    /**
     * Finds all instances of a service by its name.
     *
     * @param serviceName the name of the service
     * @return list of service registrations
     */
    List<ServiceRegistration> findByServiceName(String serviceName);

    /**
     * Finds services with a specific status.
     *
     * @param status the service status
     * @return list of services with the given status
     */
    List<ServiceRegistration> findByStatus(ServiceStatus status);

    /**
     * Finds services that contain a specific tag.
     *
     * @param tag the tag to search for
     * @return list of services containing the tag
     */
    List<ServiceRegistration> findByTagsContaining(String tag);

    /**
     * Finds services whose last heartbeat is before the specified date.
     * Useful for identifying inactive services.
     *
     * @param date the threshold date
     * @return list of services with heartbeat before the threshold
     */
    List<ServiceRegistration> findByLastHeartbeatBefore(Date date);

    /**
     * Finds services whose last heartbeat is before the specified date and whose status differs from the excluded one.
     *
     * @param date the threshold date
     * @param excludedStatus the status to exclude from results
     * @return list of matching services
     */
    List<ServiceRegistration> findByLastHeartbeatBeforeAndStatusNot(Date date, ServiceStatus excludedStatus);

    /**
     * Updates the heartbeat timestamp for a service instance.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     * @param heartbeat the new heartbeat timestamp
     */
    void updateHeartbeat(String serviceName, String instanceId, Date heartbeat);

    /**
     * Updates heartbeat and status in a single repository operation.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     * @param heartbeat the new heartbeat timestamp
     * @param status the status to set
     * @return true if a row was updated, false otherwise
     */
    boolean updateHeartbeatAndStatus(String serviceName, String instanceId, Date heartbeat, ServiceStatus status);

    /**
     * Updates the status of a service instance.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     * @param status the new status
     */
    void updateStatus(String serviceName, String instanceId, ServiceStatus status);
}
