package it.water.service.discovery.api;

import it.water.core.api.service.BaseEntitySystemApi;
import it.water.core.api.repository.query.Query;
import it.water.service.discovery.model.ServiceRegistration;
import it.water.service.discovery.model.ServiceStatus;

import java.util.List;
import java.util.Map;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for service registration
 * and allows interaction with it bypassing the permission system.
 *
 * SystemApi without permission checks - for internal framework use only.
 */
public interface ServiceRegistrationSystemApi extends BaseEntitySystemApi<ServiceRegistration> {

    /**
     * Registers a service instance internally without permission checks.
     * Used for system-level service registration.
     *
     * @param service the service registration to create
     * @return the registered service
     */
    ServiceRegistration registerInternal(ServiceRegistration service);

    /**
     * Deregisters a service instance by logical key.
     *
     * @param serviceName logical service name
     * @param instanceId runtime instance identifier
     */
    void deregisterByKey(String serviceName, String instanceId);

    /**
     * Updates the heartbeat timestamp for a service instance and marks it as UP.
     *
     * @param serviceName logical service name
     * @param instanceId runtime instance identifier
     */
    boolean updateHeartbeatInternal(String serviceName, String instanceId);

    /**
     * Performs batch health check on all registered services.
     *
     * @return map of instanceId -> ServiceStatus
     */
    Map<String, ServiceStatus> performBatchHealthCheck();

    /**
     * Cleans up inactive services by marking them as OUT_OF_SERVICE.
     * Services are considered inactive if their last heartbeat is older
     * than the specified threshold.
     *
     * @param inactiveThresholdSeconds the inactivity threshold in seconds
     */
    void cleanupInactiveServices(int inactiveThresholdSeconds);

    /**
     * Finds services by status bypassing permission checks.
     *
     * @param status the service status
     * @return list of matching services
     */
    List<ServiceRegistration> findByStatus(ServiceStatus status);

    /**
     * Finds services using a custom query.
     * Bypasses permission system for internal operations.
     *
     * @param query the custom query
     * @return list of matching services
     */
    List<ServiceRegistration> findByCustomQuery(Query query);

    /**
     * Updates the status of a service instance.
     *
     * @param serviceName the name of the service
     * @param instanceId the unique instance identifier
     * @param status the new status
     */
    void updateStatus(String serviceName, String instanceId, ServiceStatus status);
}
