package it.water.service.discovery.repository;

import it.water.core.api.repository.query.Query;
import it.water.core.interceptors.annotations.*;
import it.water.repository.entity.model.exceptions.NoResultException;
import it.water.repository.jpa.WaterJpaRepositoryImpl;
import it.water.service.discovery.api.*;
import it.water.service.discovery.model.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Date;
import java.util.List;

/**
 * @Generated by Water Generator
 * Repository Class for ServiceRegistration entity.
 *
 * Implements custom query methods for service discovery operations.
 */
@FrameworkComponent
public class ServiceRegistrationRepositoryImpl extends WaterJpaRepositoryImpl<ServiceRegistration> implements ServiceRegistrationRepository {

    private static final Logger logger = LoggerFactory.getLogger(ServiceRegistrationRepositoryImpl.class);
    private static final String SERVICEREGISTRATION_PERSISTENCE_UNIT = "serviceRegistration-persistence-unit";

    public ServiceRegistrationRepositoryImpl() {
        super(ServiceRegistration.class, SERVICEREGISTRATION_PERSISTENCE_UNIT);
    }

    @Override
    public ServiceRegistration findByServiceNameAndInstanceId(String serviceName, String instanceId) {
        logger.debug("Finding service registration by serviceName: {} and instanceId: {}", serviceName, instanceId);
        // Water Framework pattern: Use QueryBuilder for all queries
        Query query = getQueryBuilderInstance()
            .field("serviceName").equalTo(serviceName)
            .and(getQueryBuilderInstance().field("instanceId").equalTo(instanceId));
        try {
            return find(query);
        } catch (NoResultException e) {
            logger.debug("No service registration found for serviceName: {} and instanceId: {}", serviceName, instanceId);
            return null;
        }
    }

    @Override
    public List<ServiceRegistration> findByServiceName(String serviceName) {
        logger.debug("Finding all service registrations by serviceName: {}", serviceName);
        // Water Framework pattern: Use QueryBuilder for all queries
        Query query = getQueryBuilderInstance()
            .field("serviceName").equalTo(serviceName);
        return findAll(-1, 1, query, null).getResults().stream().toList();
    }

    @Override
    public List<ServiceRegistration> findByStatus(ServiceStatus status) {
        logger.debug("Finding all service registrations by status: {}", status);
        // Water Framework pattern: Use QueryBuilder with string filter for enum types
        Query query = getQueryBuilderInstance().createQueryFilter("status='" + status.name() + "'");
        return findAll(-1, 1, query, null).getResults().stream().toList();
    }

    @Override
    public List<ServiceRegistration> findByTagsContaining(String tag) {
        logger.debug("Finding all service registrations containing tag: {}", tag);
        // Water Framework pattern: Use QueryBuilder for all queries
        // QueryBuilder abstracts collection JOINs - query the collection field directly
        Query query = getQueryBuilderInstance()
            .field("tags").equalTo(tag);
        return findAll(-1, 1, query, null).getResults().stream().toList();
    }

    @Override
    public List<ServiceRegistration> findByLastHeartbeatBefore(Date date) {
        logger.debug("Finding all service registrations with lastHeartbeat before: {}", date);
        // Water Framework pattern: Use QueryBuilder for all queries
        Query query = getQueryBuilderInstance()
            .field("lastHeartbeat").lowerThan(date);
        return findAll(-1, 1, query, null).getResults().stream().toList();
    }

    @Override
    public void updateHeartbeat(String serviceName, String instanceId, Date heartbeat) {
        logger.debug("Updating heartbeat for serviceName: {} and instanceId: {} to: {}", serviceName, instanceId, heartbeat);
        // Water Framework pattern: find-then-update
        ServiceRegistration entity = findByServiceNameAndInstanceId(serviceName, instanceId);
        if (entity != null) {
            entity.setLastHeartbeat(heartbeat);
            update(entity);
        } else {
            logger.warn("No service registration found for serviceName: {} and instanceId: {}", serviceName, instanceId);
        }
    }

    @Override
    public void updateStatus(String serviceName, String instanceId, ServiceStatus status) {
        logger.debug("Updating status for serviceName: {} and instanceId: {} to: {}", serviceName, instanceId, status);
        // Water Framework pattern: find-then-update
        ServiceRegistration entity = findByServiceNameAndInstanceId(serviceName, instanceId);
        if (entity != null) {
            entity.setStatus(status);
            update(entity);
        } else {
            logger.warn("No service registration found for serviceName: {} and instanceId: {}", serviceName, instanceId);
        }
    }
}