package it.water.service.discovery.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import it.water.core.api.entity.owned.OwnedResource;
import it.water.core.api.permission.ProtectedEntity;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AccessControl;
import it.water.core.permission.annotations.DefaultRoleAccess;
import it.water.core.validation.annotations.NoMalitiusCode;
import it.water.core.validation.annotations.NotNullOnPersist;
import it.water.repository.jpa.model.AbstractJpaEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.util.Date;
import java.util.Map;
import java.util.Set;

/**
 * @Generated by Water Generator
 * ServiceRegistration Entity Class.
 * <p>
 * Represents a service registered in the Service Discovery system.
 * Tracks service identity, health status, and reserved extension payloads.
 */
@Entity
@Table(name = "service_registration",
        uniqueConstraints = @UniqueConstraint(columnNames = {"serviceName", "instanceId"}))
@Access(AccessType.FIELD)
// Lombok
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Getter
@Setter(AccessLevel.PROTECTED)
@ToString
@EqualsAndHashCode(of = {"serviceName", "instanceId"}, callSuper = true)
// Actions and default roles access
@AccessControl(
        availableActions = {
                CrudActions.SAVE,
                CrudActions.UPDATE,
                CrudActions.FIND,
                CrudActions.FIND_ALL,
                CrudActions.REMOVE,
                ServiceDiscoveryActions.HEALTH_CHECK
        },
        rolesPermissions = {
                @DefaultRoleAccess(
                        roleName = ServiceRegistration.DEFAULT_MANAGER_ROLE,
                        actions = {
                                CrudActions.SAVE,
                                CrudActions.UPDATE,
                                CrudActions.FIND,
                                CrudActions.FIND_ALL,
                                CrudActions.REMOVE,
                                ServiceDiscoveryActions.HEALTH_CHECK
                        }
                ),
                @DefaultRoleAccess(
                        roleName = ServiceRegistration.DEFAULT_VIEWER_ROLE,
                        actions = {CrudActions.FIND, CrudActions.FIND_ALL}
                ),
                @DefaultRoleAccess(
                        roleName = ServiceRegistration.DEFAULT_OPERATOR_ROLE,
                        actions = {
                                CrudActions.FIND,
                                CrudActions.FIND_ALL,
                                CrudActions.UPDATE,
                                ServiceDiscoveryActions.HEALTH_CHECK
                        }
                )
        }
)
public class ServiceRegistration extends AbstractJpaEntity implements ProtectedEntity, OwnedResource {

    public static final String DEFAULT_MANAGER_ROLE = "serviceDiscoveryManager";
    public static final String DEFAULT_VIEWER_ROLE = "serviceDiscoveryViewer";
    public static final String DEFAULT_OPERATOR_ROLE = "serviceDiscoveryOperator";

    // ========== Service Identification ==========

    @NoMalitiusCode
    @NotNull
    @NotNullOnPersist
    @Size(min = 1, max = 255)
    @Column(nullable = false, length = 255)
    @Setter
    @JsonView(WaterJsonView.Public.class)
    private String serviceName;

    @NoMalitiusCode
    @NotNull
    @NotNullOnPersist
    @Size(min = 1, max = 50)
    @Column(nullable = false, length = 50)
    @Setter
    @JsonView(WaterJsonView.Public.class)
    private String serviceVersion;

    @NoMalitiusCode
    @NotNull
    @NotNullOnPersist
    @Size(min = 1, max = 255)
    @Column(nullable = false, length = 255)
    @Setter
    @JsonView(WaterJsonView.Public.class)
    private String instanceId;

    // ========== Networking ==========

    @NoMalitiusCode
    @NotNull
    @NotNullOnPersist
    @Size(min = 1, max = 500)
    @Column(nullable = false, length = 500)
    @Setter
    @JsonView(WaterJsonView.Public.class)
    private String endpoint;

    @NoMalitiusCode
    @NotNull
    @NotNullOnPersist
    @Size(min = 1, max = 50)
    @Column(nullable = false, length = 50)
    @Setter
    @JsonView(WaterJsonView.Public.class)
    private String protocol;

    // ========== Metadata ==========

    @NoMalitiusCode
    @Column(length = 2000)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private String description;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "service_registration_tags",
            joinColumns = @JoinColumn(name = "service_registration_id"))
    @Column(name = "tag")
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private Set<String> tags;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "service_registration_metadata",
            joinColumns = @JoinColumn(name = "service_registration_id"))
    @MapKeyColumn(name = "metadata_key", length = 255)
    @Column(name = "metadata_value", length = 1000)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    // Reserved extension point: persisted and exposed, but not interpreted by
    // the core registry logic.
    private Map<String, String> metadata;

    // ========== Health & Lifecycle ==========

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    @Setter
    @JsonView(WaterJsonView.Public.class)
    private ServiceStatus status;

    @Temporal(TemporalType.TIMESTAMP)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private Date lastHeartbeat;

    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private Integer healthCheckInterval;

    @NoMalitiusCode
    @Size(max = 500)
    @Column(length = 500)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private String healthCheckEndpoint;

    // ========== Configuration ==========

    @Lob
    @Column(length = 10000)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    // Reserved extension point for future runtime-specific payloads. Kept as
    // part of the REST/entity contract even if the current module does not use it.
    private String configuration;

    // ========== Owned Resource ==========

    @Setter
    @JsonIgnore
    @JsonView({WaterJsonView.Extended.class})
    private Long ownerUserId;

    // ========== Constructors ==========

    /**
     * Public constructor for creating ServiceRegistration with required fields.
     * For testing and manual instantiation purposes.
     *
     * @param serviceName    the name of the service
     * @param serviceVersion the version of the service
     * @param instanceId     the unique instance identifier
     * @param endpoint       the service endpoint URL
     * @param protocol       the protocol used (http, https, grpc, etc.)
     * @param status         the initial service status
     */
    public ServiceRegistration(String serviceName, String serviceVersion, String instanceId,
                               String endpoint, String protocol, ServiceStatus status) {
        this.serviceName = serviceName;
        this.serviceVersion = serviceVersion;
        this.instanceId = instanceId;
        this.endpoint = endpoint;
        this.protocol = protocol;
        this.status = status;
    }

    // ========== Public Setters for Testing ==========

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public void setServiceVersion(String serviceVersion) {
        this.serviceVersion = serviceVersion;
    }

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(ServiceStatus status) {
        this.status = status;
    }

    public void setLastHeartbeat(Date lastHeartbeat) {
        this.lastHeartbeat = lastHeartbeat;
    }

    // ========== Lifecycle Hooks ==========

    @PrePersist
    protected void onCreate() {
        if (this.lastHeartbeat == null) {
            this.lastHeartbeat = new Date();
        }
        if (this.status == null) {
            this.status = ServiceStatus.STARTING;
        }
    }
}
